name: Build

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
 
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=10m
          version: latest
      
      - name: Run Tests
        run: make test

      - name: Install poetry
        run: pipx install poetry
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --no-root

      - name: Create a virtual environment
        run: poetry shell

      - name: Run Integration Tests
        run: make integration-test

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}